---
- hosts: 172.31.5.120
  tasks:  
  - name: install apache
    yum:
      name: httpd
      state: present
  - name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: ansible.html
    dest: /var/www/html/
    owner: root
    group: root
    mode: '0644'
          
