---
- hosts: 172.31.5.120
  tasks:  
  - name: install apache
    yum:
        name: httpd
        state: present
  - name: copy code to remote machine
    copy: 
       src: ansible.html
       dest: /var/www/html/
