- name: Install Apache
  hosts: 172.31.5.120
  become: true
  tasks:
  - name: Install Apache
    yum:
      name: httpd
      state: latest
  - name: Enable apache
    services:
      name: httpd
      state: started
      enaled: yes
  - name: Copy file
    copy:
      src: ~/ansible.html
      dest: /var/www/html
