---
- hosts: 172.31.5.120
  tasks:  
  - name: install apache
    yum:
      name: httpd
      state: present
  - name: copy code to remote machine
    copy: 
       src: ansible.html
       dest: /var/www/html/
- name: Start service httpd, if not started
  ansible.builtin.service:
    name: httpd
    state: started
          
