---
- hosts: 172.31.5.120
  become: True
  tasks:  
  - name: install apache
    yum:
        name: httpd
        state: present
    -name: copy file to remote machine
     copy:
         src: ansible.html
         dest: /var/www/html/
        
